### PR TITLE
Enhance 404 Not Found Page

### PR DESCRIPTION
**Pull request by Dhruv-Sood**
This PR addresses the issue #26

### CODE REVIEW

**Review by LeeBingler — CHANGES_REQUESTED** [review]
I'm sorry but i can't accept this pull request. I've told you that i wanted something in the general design of the site, so something professional and minimalist.

I have not been clear on this point so it's my bad there.

**Comment by Dhruv-Sood** [comment]
Okay, I'll try to keep it simple. I will add an image for the error, can you tell me in what directory should I keep the image in?

**Comment by LeeBingler** [comment]
Public i guess ?

**Comment by Dhruv-Sood** [comment]
I updated the Error page!!
Please check

**Review by LeeBingler — APPROVED** [review]

**Comment by LeeBingler** [comment]
That's really impressive thank you a lot for that

**Comment by Dhruv-Sood** [comment]
No Problem😊

**Pull request merged**
